# OPTIONAL: path to the composer binary file to use. If not specified, the script will
# attempt to locate it. The script will fail if it cannot be found and verified.
composer_path: ''
# OPTIONAL: path to the git binary file to use. If not specified, the script will
# attempt to locate it. The script will fail if it cannot be found and verified.
git_path: ''
# OPTIONAL: path in which to write log files. If not specified, the script will attempt
# to use /var/log. If the destination is not writable, no log will be recorded and the
# email notification will mention this.
# NOTE: NO TRAILING SLASH!
log_file_path: ''
# OPTIONAL: A script to run after updates are completed and committed. This could be useful
# if, for example, you need automatically correct file permissions once the update is complete.
# This command will always be run from within the site's directory.
post_update_script: ''
# OPTIONAL: List of files to diff after updates are completed, but prior to committing.
# A diff will be generated for each file and included in the email notification and
# commit message. This is useful if you want to monitor changes to specific files for
# manual review.
post_update_diff_files:
  - '[docroot]/.htaccess'
# OPTIONAL: Similar to post_update_diff_files, but in addition to generating a diff, the
# files will be reverted to their original state prior to committing. WARNING: this list
# will take precedence over post_update_diff_files, so if you include a file in both lists,
# it will be reverted.
post_update_revert_files: {  }
# REQUIRED: Whether or not to sanitize the local database after syncing from production.
sanitize_databases_on_sync: true
# OPTIONAL: whether or not to always send an email notification after updates are completed.
# If false or not specified, an email will only be sent if the --notify flag is used when running
# the script.
always_notify: false
# REQUIRED: Email settings.
mail:
  # REQUIRED: Notification email address.
  notification_email: 'johnny.appleseed@example.com'
  # REQUIRED: The SMTP hostname to send email through.
  smtp_host: 'your.smtp.host'
  # REQUIRED: The SMTP port to send email through.
  smtp_port: 25
  # REQUIRED: Whether or not to use TLS encryption.
  use_tls: true
  # OPTIONAL: The SMTP username.
  smtp_user: ''
  # OPTIONAL: The SMTP password.
  smtp_pass: ''
  # REQUIRED: From email address (without name).
  from_email: 'johnny.appleseed@example.com'
  # REQUIRED: From name for sending emails.
  from_email_name: 'Johnny Appleseed'
# REQUIRED: Git settings.
git:
  # REQUIRED: The git repository remote key.
  remote_key: 'origin'
  # REQUIRED: Git commit author. Must be in the proper format, or errors will occur
  # when committing resulting in the script failing.
  commit_author: 'Johnny Appleseed <johnny.appleseed@example.com>'
  # OPTIONAL: The name of the main git branch to use. If not specified, the script
  # will attempt to use 'master'.
  main_branch: ''
  # OPTIONAL: The name of the branch to use for updates. If not specified, the script
  # will attempt to use 'drupal-updates'.
  update_branch: ''
